services:
  cyber-integration:
    image: cyber-integration:latest
    container_name: cyber-integration
    build:
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
  cyber-integration-test:
    image: cyber-integration-test:latest
    container_name: cyber-integration-test
    build:
      target: test
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - ./coverage/:/app/coverage
      - ./package.json:/app/package.json
    command: npm run test:cov
