steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "build"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: "push_image"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"

  - name: "gcr.io/pravaler-tools-devops/cloud-builder-deployer:v3"
    id: "deploy_image"
    args:
      - "--project-id"
      - "$PROJECT_ID"
      - "--ps-app-name"
      - "cyber-integration"
      - "--ps-branch-name"
      - "$BRANCH_NAME"
      - "--ps-short-sha"
      - "$SHORT_SHA"
      - "--ps-deploy-type"
      - "helm"
      - "--ps-repo-name"
      - "$REPO_NAME"

options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: "projects/$PROJECT_ID/locations/us-east1/workerPools/default"